[CMOB-1294]basic design implementation
iTarley/ChatApp-SpaceIntern pull request #1
Opened 2023-04-13 13:32 UTC by iTarley

https://spaceneobank.atlassian.net/browse/CMOB-1294

basic project setup + no canvas design setup (not final version)

2023-04-13 13:37 UTC, bchmsl approved these changes
Drawable ფაილებს უფრო კონკრეტული სახელი დაარქვი

2023-04-13 14:00 UTC, Gio481 requested changes

2023-04-13 14:00 UTC, Gio481 commented on app/src/main/res/values/strings.xml
>  </resources>
ეს ორი სტრინგი ზედმეტია არაფერში გამოიყენებ, წინასწარ ხო არ იცი რა დროს და რა მესიჯს დაწერს ამ შემთხვევაში tools ატრიბუტი გამოიყენე რო ვიუს გაკეთების მომენტში შენთვის შეგეძლება დანახვა პროსტა რა ეწერება ან რამე მსგავსი და აპის დაბილდვისას არ გამოგიჩნდება

2023-04-13 14:44 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/MainActivity.kt
>          val view = binding.root
done

2023-04-13 14:44 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/main/FirstFragment.kt
> +class FirstFragment : Fragment() {
done

2023-04-13 14:44 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/main/SecondFragment.kt
> +}
done(ეგ არ გავაკეთე რადგან ჯერ xml ვალაგებდი)

2023-04-13 14:44 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/main/SecondViewModel.kt
> +class SecondViewModel : ViewModel() {
done

2023-04-13 14:44 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/main/SecondFragment.kt
> +package com.example.chatapp_spaceintern.presentation.main
done

2023-04-13 14:45 UTC, iTarley commented on app/src/main/res/layout/send_from_message.xml
> +        android:id="@+id/constraintLayout"
done(მეც არ ვიცი)

2023-04-13 14:45 UTC, iTarley commented on app/src/main/res/layout/send_from_message.xml
> +        android:textSize="8sp"
done (ეგ არ ვიცოდი, მადლობა!)

2023-04-13 14:45 UTC, iTarley commented on app/src/main/res/layout/send_to_message.xml
> +        app:layout_constraintTop_toTopOf="parent">
ამის გარეშე გაფუჭდება ყველაფერი, ჯერ იყოს მერე რაღაცას აუცილებლად მოვიფიქრებ

2023-04-13 14:46 UTC, iTarley commented on app/src/main/res/values/strings.xml
>  </resources>
done (tool-ის არსებობა საერთოდ დამავიწყდა)

2023-04-13 14:49 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/chatapp_spaceintern/MainActivity.kt
> +        fm.beginTransaction().replace(R.id.bottomFragment, BottomFragment()).commit()
u can write like this supportFragmentManager.apply {#1 replace, #2 replace }, more readable and less variable :)

2023-04-13 14:51 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_top.xml
> +
pls avoid extra lines )

2023-04-13 14:53 UTC, iTarley commented on app/src/main/res/layout/fragment_top.xml
> +
ctrl + L მავიწყდება ხოლმე, შევეცდები რომ გამოვასწორო

2023-04-13 14:56 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/values/text_style.xml
> +        <item name="android:textColor">#191919</item>
move color into color resource file

2023-04-13 14:57 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/send_to_message.xml
> +        android:textColor="#C7C7C7"
move color into resource file

2023-04-13 14:58 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/MainActivity.kt
> +        fm.beginTransaction().replace(R.id.bottomFragment, BottomFragment()).commit()
done

2023-04-13 15:02 UTC, iTarley commented on app/src/main/res/layout/send_to_message.xml
> +        android:textColor="#C7C7C7"
done

2023-04-13 15:02 UTC, iTarley commented on app/src/main/res/values/text_style.xml
> +        <item name="android:textColor">#191919</item>
done

2023-04-13 15:02 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_top.xml
> +
უნდა ამოიღო ექსტრა ლაინები, ერთი ლაინი გამოტოვება ჯდება კარგად xml ვიუებს შორის და კოდში მეთოდებს შორის

2023-04-13 15:25 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/fragment_top.xml
> +
exta line here

2023-04-13 15:25 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/send_from_message.xml
> +
exta line here

2023-04-13 15:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/send_from_message.xml
> +
here also, please remove all extra lines )))

2023-04-13 15:33 UTC, iTarley commented on app/src/main/res/layout/send_from_message.xml
> +
done

2023-04-15 09:27 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
> +    private val inflate: Inflate<VB>
კონსტრუქტორში ჩაწოდებას გირჩევნია აბსტრაქტული ფუნქცია ან ცვლადი იყოს ინფლეიტი

2023-04-15 09:27 UTC, Gio481 commented on app/src/main/res/values/text_style.xml
> +    <style name="BasicTextSetting" parent="TextAppearance.AppCompat">
ესე სტილი კაია, პროსტა შენვე რო მიხვდე რომელ სტილს იყენებ დაარქვი mediumMyriadGeo_Normal, ან small ან რამე Normal ნიშნავს რო ბოლდი არაა თუ ბოლდი იქნება mediumMyriadGeo_Bold და ასე შემდეგ

2023-04-15 09:27 UTC, Gio481 commented on app/src/main/res/values/text_style.xml
> +        <item name="android:textSize">14sp</item>
ასევე 14 სპ რესურსებშია გასატანი

2023-04-15 09:27 UTC, Gio481 commented on app/src/main/res/values/text_style.xml
> +        <item name="android:textColor">@color/textMainColor</item>
textMainColor მე ვერ გავიგე რომელი ფერია, უნდა გადავიდე რესურსებში ვნახო რომელი ფერია და თუ მაწყობს მერე გამოვიყენო ჯობია პირდაპირვე დაარქვა რა ფერიცაა და თუ ვთქვათ სამი ყვითელი გაქვს შეგიძლია დაარქვა yellow_200, yellow_500 ღიიდან მუქისკენ რა ხო ხვდები

2023-04-15 10:20 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
> +    private val inflate: Inflate<VB>
done (არ ვიცი რამდენად სწორად ეხლა მაქვს 🙃🙃)

2023-04-15 10:20 UTC, iTarley commented on app/src/main/res/values/text_style.xml
> +    <style name="BasicTextSetting" parent="TextAppearance.AppCompat">
done (გავითვალისწინებ მაგას აუცილებლად)

2023-04-15 10:20 UTC, iTarley commented on app/src/main/res/values/text_style.xml
> +        <item name="android:textSize">14sp</item>
done (ეგ არ ვიცოდი)

2023-04-15 10:20 UTC, iTarley commented on app/src/main/res/values/text_style.xml
> +        <item name="android:textColor">@color/textMainColor</item>
done (მაგასაც გავითვალისწინებ მომავალში)

2023-04-15 18:15 UTC, Gio481 commented on app/src/main/res/layout-land/activity_main.xml
> +            android:visibility="visible" />
დეფოლტად ხილვადია ისეც წაუშალე ვისიბილითი

2023-04-15 18:16 UTC, Gio481 commented on app/src/main/res/layout/activity_main.xml
> +            android:visibility="visible" />
აქაც არ გინდა ვისიბილითი

2023-04-15 18:17 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/bottom_screen/BottomFragment.kt
> +        return FragmentBottomBinding::inflate
onBind ფუნქცია ქვემოთ დაუწერე ხო ლოგიკები ხო მანდაა დასაწერი

2023-04-15 18:18 UTC, Gio481 commented
@iTarley სადაც dp და sp გაქვს გაიტანე დიმენშენების რესურსებში და სახელები დაარქვი dimen_10_dp ან dimen_10_sp და ასე შემდეგ

2023-04-15 18:18 UTC, Gio481 approved these changes

2023-04-15 18:20 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/bottom_screen/BottomFragment.kt
> +        return FragmentBottomBinding::inflate
ის რაც ფრაგმენტებში მიწერია გამოსწორებულია ყველაფერი, უბრალოდ ველოდებოდი მაგის accept-ი რომ გავუშვა ახალი კომითი ბიზნეს ლოგიკით

2023-04-15 18:28 UTC, iTarley commented on app/src/main/res/layout/activity_main.xml
> +            android:visibility="visible" />
done

2023-04-15 18:28 UTC, iTarley commented on app/src/main/res/layout-land/activity_main.xml
> +            android:visibility="visible" />
done

2023-04-17 11:41 UTC, AleksandreGalogreBaramidze approved these changes

2023-04-17 11:41 UTC, AleksandreGalogreBaramidze commented on app/src/main/res/drawable/dividerline.xml
> +      android:fillColor="#F7CE7F"/>
კარგი იქნება თუ ფერებსაც რესურს ფაილებში გაიტან

2023-04-17 11:43 UTC, iTarley commented on app/src/main/res/drawable/dividerline.xml
> +      android:fillColor="#F7CE7F"/>
მართალი ხარ, გამომრჩა

2023-04-17 11:45 UTC, GiorgiMamagulashvil1 approved these changes

2023-04-17 11:46 UTC, ninikokra approved these changes
<3

2023-04-17 12:47 UTC, merged