[CMOB-1304]Business logic implementation
iTarley/ChatApp-SpaceIntern pull request #2
Opened 2023-04-17 14:20 UTC by iTarley

https://spaceneobank.atlassian.net/browse/CMOB-1304

2023-04-17 16:27 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +                        internet = true
ეგ ზედმეტი value არი ჯერჯერობით, მერე წავშლი

2023-04-17 16:27 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/model/MessageModel.kt
> +    val internet:Boolean?
ზედმეტია

2023-04-17 16:27 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/entity/ChatEntity.kt
> +    val internet: Boolean?
ზედმეტია

2023-04-17 16:28 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +                        internet = true
Internet

2023-04-17 16:28 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/entity/ChatEntity.kt
> +    val internet: Boolean?
Internet

2023-04-17 17:58 UTC, GiorgiMamagulashvil1 requested changes

2023-04-17 17:58 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +            ContextCompat.getDrawable(baseContext, R.drawable.night_day_switch)
create extension method for get drawable functionality and use that

2023-04-17 17:58 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +    }
here also use with(binding)

2023-04-17 17:58 UTC, GiorgiMamagulashvil1 commented on app/src/main/res/layout/send_from_message.xml
>              android:layout_height="wrap_content"
use margin vertical in this view )

2023-04-17 17:58 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/chatapp_spaceintern/App.kt
> +        GlobalContext.startKoin {
u dont need GlobalContext, u can call startKoin directly

2023-04-17 18:02 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/di/AppModule.kt
> +    }
That's my first Koin experience, so i used first stack overflow answer, anyway big thanks for commentaries. I will try my best to fix all of them ♥️

2023-04-17 18:04 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/di/AppModule.kt
> +    }
Should i write all this methods in AppModule.kt ? Or it would be better in separate class/file?

2023-04-17 19:55 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +                        internet = true
done

2023-04-17 19:55 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/model/MessageModel.kt
> +    val internet:Boolean?
done

2023-04-17 19:55 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/entity/ChatEntity.kt
> +    val internet: Boolean?
done

2023-04-17 20:03 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/chatapp_spaceintern/di/AppModule.kt
> +    }
It depends on your code style, i prefer separate modules but in your case u can write in one module bcs app is small, everything else was fine 🪐

2023-04-17 20:46 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +    }
done

2023-04-17 20:47 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +        }
done

2023-04-17 20:47 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +                }
done

2023-04-17 20:47 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +    }
done

2023-04-17 20:47 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +            ContextCompat.getDrawable(baseContext, R.drawable.night_day_switch)
done

2023-04-17 20:48 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +            if (isNetworkAvailable(context)) {
I think we should avoid using Context in ViewModel, later I will try to rewrite internet handling with broadcast receiver or something like that

2023-04-17 20:48 UTC, iTarley commented on app/src/main/res/layout/send_from_message.xml
>              android:layout_height="wrap_content"
done

2023-04-17 20:48 UTC, iTarley commented on app/src/main/res/layout/send_to_message.xml
>              android:layout_height="wrap_content"
done

2023-04-17 20:48 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/App.kt
> +        GlobalContext.startKoin {
done, thanks

2023-04-17 20:54 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/di/AppModule.kt
> +    }
I spent a little more time studying koin, now it makes more sense to me. I used similar logic as in dagger-hilt, separate file for room,dataStore and etc. Thanks for advice!!

2023-04-18 04:21 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivityViewModel.kt
> +    fun dayNightHandling(dayNightMode:() ->Unit, nightDayMode:() ->Unit){
I think lambdas is wrong there, better would be create two state for day/light theme and observe in activity and call this methods in observer

2023-04-18 10:08 UTC, gioqemoklidze requested changes

2023-04-18 10:08 UTC, gioqemoklidze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
შეგილია ვიუმოდელიც აქ შეაქმნევინო და მერე ამ ფუნქციას სახელი გადაარქვა onBindViewModel(viewModel: VM)

2023-04-18 10:20 UTC, AnaRusadze requested changes

2023-04-18 10:20 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/adapter/RecyclerAdapter.kt
> +    inner class TopViewHolder(private val binding: SendToMessageBinding) :
ვიუ ჰოლდერის ინერ კლასად გამოცხადებას შეიძლება მემორი ლიქამდე მიგვიყვანოს, რადგან ინერ კლასი ადაპტერის რეფერენსს შეინახავს მაშინაც, როცა ადაპტერი არ დაგვჭირდება და მისი სასიცოცხლო ციკლი აქტიური არ იქნება. რა თქმა უნდა ახლა საფრთხე არ არის, ეს შეიძლება მოხდეს ძალიან ბევრი რაოდენობის აითემის შემთხვევაში, მაგრამ კარგი იქნება თუ მოძებნი პრაქტიკას, სადაც ვიუჰოლდერი ინერ კლასი არ იქნება

2023-04-18 10:20 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/adapter/RecyclerAdapter.kt
> +    }
binding.apply{} ის შემთხვევაში შეგიძლია binding აღარ ჩაწერო 
binding.apply {
                sendToTextView.text = currentMessage.message
                dateTextViewTo.text = currentMessage.time
            }
თუმცა ამ შემთხვევაში binding.apply{} გვიბრუნებს ბაინდინგის ობიექტს, რითიც სხვადასხვა მოდიფიკაციების გაკეთების საშუალება გვაძლევს ამ ობიექტზე, რაც არ გვჭირდება, ამიტომ გამოიყენე

with(binding){}. ორივე კოტლინის ექსთენშენია, უბრალოდ with() საშუალებას გვაძლევს მივწვდეთ ბაინდინგის შიგნით არსებულ ვიუებს ობიექტის დაბრუნების გარეშე. სფეისშიც ვიყენებთ with-ს

2023-04-18 10:20 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +        private const val SENDER = "BOTTOM"
თუ ადაპტერს გადასცემ ენამს სტრინგის მაგივრად, ეს ცვლადი აღარ დაგჭირდება

2023-04-18 10:20 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +            Toast.makeText(context, getString(R.string.check_internet), Toast.LENGTH_SHORT).show()
შექმენი ტოასტი, როგორც კონტექსტის ექსთენშენი

2023-04-18 10:20 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/InternetCheck.kt
> +fun isNetworkAvailable(context: Context?): Boolean {
კონტექსტის ექსთენშენად გადააკეთე და ფაილს კონტექსტის ექსთენშენი დაარქვი, მანდვე დაამატე ტოუსტის ექსთენშენიც

2023-04-18 10:20 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="check_internet">Check your internet connection</string>
რადგან ქართული აპლიკაცია გვაქვს, ინტერნეტის შემოწმებაც ქართულად დაწერე

2023-04-18 11:29 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
I personally don't like having a viewmodel in my base fragment, base fragment's primary responsibility is typically to provide common UI-related functionality, and adding ViewModel functionality to it can lead to a violation of SRP, making the code harder to understand and maintain

2023-04-18 11:29 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
If I'm wrong, please correct

2023-04-18 11:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +                .commit()
maybe a little later, I don't want to break what's working now.

2023-04-18 11:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
done

2023-04-18 11:49 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/repository/DataStoreRepositoryImpl.kt
> +        private const val KEY_BOOL = "BOOLEAN"
instead of KEY_BOOL , now I have STRING_KEY 😅, I didn't fully understand this "key" thing.

2023-04-18 11:52 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/SendMessageUseCase.kt
> +    suspend fun invoke(chat:MessageModel) = repository.insertAll(chat)
done❤️

2023-04-18 12:10 UTC, iTarley commented on app/src/main/res/values/strings.xml
> +    <string name="check_internet">Check your internet connection</string>
done

2023-04-18 12:10 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/InternetCheck.kt
> +fun isNetworkAvailable(context: Context?): Boolean {
done

2023-04-18 12:10 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +            Toast.makeText(context, getString(R.string.check_internet), Toast.LENGTH_SHORT).show()
done

2023-04-18 12:10 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +        private const val SENDER = "BOTTOM"
To be honest, I didn't understand it.

2023-04-18 12:10 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/adapter/RecyclerAdapter.kt
> +    }
done, thanks

2023-04-18 12:10 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +            replace(binding.bottomFragment.id, BottomFragment())
done, I didn't know about that

2023-04-18 12:23 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/repository/ChatMessageRepositoryImpl.kt
> +class ChatMessageRepositoryImpl(private val db: AppDataBase) : ChatMessageRepository {
კონსტრუქტორში dao ჩააწოდე დათაბაზის ნაცვლად

2023-04-18 12:25 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/di/RoomModule.kt
> +}
![databasemodule](https://user-images.githubusercontent.com/70803715/232776378-49b53db2-15ab-4781-9ece-9a1c22470585.JPG)

შეგიძლია ასეთი მიდგომა გამოიყენო უფრო გარჩევადია და წასაკითხადაც გასაგებია და room არა database module გადაარქვი

2023-04-18 12:26 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/di/UseCaseModule.kt
> +    }
ან მესამე იუს ქეისიც დააშორე ან მეორეს წაუშალე დაშორება :დ

2023-04-18 12:29 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +        }
lifecycleScope.launch ექსთენშენი გააკეთე

2023-04-18 12:30 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivityViewModel.kt
> +        }
viewModelScore.launch ექსთენშენიც გააკეთე

2023-04-18 12:35 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/DateExtansion.kt
> +    return dayMonthFormat.format(calendar.time) + "," + timeFormat.format(calendar.time)
შეგიძლია ასე გქონდეს dd/MM, HH:mm ერთ ცვლადში

2023-04-18 12:36 UTC, Gio481 commented on build.gradle
> +    }
ესეც წასაშლელია არ იყენებ ხო ამას

2023-04-18 12:51 UTC, gioqemoklidze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
ვიუმოდელთან წვდომაც ui ს ნაწილია შენ მარტო ვიუმოდელის ინსტანსი გჭიდება ბეის ფრაგმენტში და ვიუმოდელის მეთოდებს ჩვეულებრივად გამოიძახებ ჩაილდ ფრაგმენტში

2023-04-18 12:51 UTC, gioqemoklidze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
@iTarley

2023-04-18 12:52 UTC, gioqemoklidze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +                .commit()
ოქეი შემდეგ პრში ერთ ფრაგმენტზე გადააწყე

2023-04-18 13:02 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/domain/local/repository/ChatMessageRepository.kt
> +package com.example.chatapp_spaceintern.domain.local.repository
local ფექიჯი არ უნდა პირდაპირ რეპოსიტორის ფოლდერი იყოს

2023-04-18 13:18 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
კარგია რო ვიუმოდელის ინიცაილიზება და მისი რეფერენსები ერთი ადგილიდან გადიოდეს, ამ შემთხვევაში უფრო ქლინი კოდი გექნება უფრო მართავ ვიუმოდელის lifecycle, არაა კარგი როცა ფრაგმენტის ყველა ადგილიდან შეგიძლია ვიუმოდელს მიწვდე, ამიტო უნდა გააკეთო რო ვიუმოდელის შექმნა მოხდეს ბეის ფრაგმენტში და ინიცალიზება უკვე იმ კონკრეტულ ფრაგმენტში

2023-04-18 13:50 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/adapter/RecyclerAdapter.kt
> +    }
done

2023-04-18 13:50 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/local/repository/ChatMessageRepository.kt
> +package com.example.chatapp_spaceintern.domain.local.repository
done

2023-04-18 13:50 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/entity/ChatEntity.kt
> +) : Parcelable
done

2023-04-18 13:50 UTC, iTarley commented on build.gradle
> +    }
done

2023-04-18 13:50 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/DateExtansion.kt
> +    return dayMonthFormat.format(calendar.time) + "," + timeFormat.format(calendar.time)
done, thanks!

2023-04-18 13:51 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +        }
I don't understand what this is for if " .launch " is already an extension function for LifecycleOwner,

anyway, done!

2023-04-18 13:51 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/di/UseCaseModule.kt
> +    }
done

2023-04-18 13:52 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/repository/ChatMessageRepositoryImpl.kt
> +class ChatMessageRepositoryImpl(private val db: AppDataBase) : ChatMessageRepository {
done

2023-04-18 13:52 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/dao/ChatDao.kt
> +    suspend fun insertAll(vararg users: ChatEntity)
done

2023-04-18 13:52 UTC, iTarley commented on app/build.gradle
> +    id 'androidx.navigation.safeargs.kotlin'
done

2023-04-18 14:14 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseDiff.kt
> +}
baseDiff ზედმეტია არ გინდა დათა კლასებზე არაფრის მიბმა და uniqueValue მაგივრად შეგიძლია hashcode() გამოიყენო

2023-04-18 15:47 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseDiff.kt
> +}
კი ვცადე გადაკეთება მაგრამ ეხლა supressLint ანოტაცია მაქვს, ჯერჯერობით არ გამომივიდა მაგის გამოსწორება

2023-04-19 11:25 UTC, AnaRusadze requested changes

2023-04-19 11:25 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/adapter/ChatRecyclerAdapter.kt
> +    inner class BottomViewHolder(private val binding: SendFromMessageBinding) :
ინერ კლასები არ გამოიყენო

2023-04-19 11:25 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +            binding.dayNightSwitcher.getDrawable(baseContext, R.drawable.day_night_switch)
binding.dayNightSwitcher.getDrawable(baseContext,  
if (AppCompatDelegate.getDefaultNightMode() == AppCompatDelegate.MODE_NIGHT_YES) R.drawable.day_night_switch else R.drawable.day_night_switch
)

შეგიძლია ასე შეამოკლო კოდი

2023-04-19 11:29 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/ui/BottomFragment.kt
> +        private const val SENDER = "BOTTOM"
შექმენი ენამის კლასი ტოპ და ბოტტომ იუზერისთვის, 
class ChatRecyclerAdapter(private val sender: String) -> ადაპტერს სენდერის სტრინგის ტიპის მაგივრად, გადაეცი ენამის ტიპის პარამეტრი. 
შემდეგ ეს ცვლადიც აღარ დაგჭირდება.

თუ რამეა, მერე რევიუზე აგიხსნი ლაივში <3

2023-04-19 11:55 UTC, iTarley commented on app/src/main/res/layout/send_to_message.xml
> +            tools:text="გამარჯობა,გამარჯობა, ჯემალიგამარჯობა, ჯემალიგამარჯობა, ჯემალიგამარჯობა, ჯემალიგამარჯობა, ჯემალიგამარჯობა,ლმალიგამარჯო, ჯემალი ჯემალი" />
თვითონ დაიწერა, მე არაფრის შუაში არ ვარ 🙂

2023-04-19 17:20 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
done

2023-04-19 17:21 UTC, iTarley commented on app/src/main/res/values/colors.xml
> +    <color name="date_basic_color_grey">#C7C7C7</color>
done

2023-04-19 19:16 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivity.kt
> +            binding.dayNightSwitcher.getDrawable(baseContext, R.drawable.day_night_switch)
indeed,thanks!

2023-04-19 19:16 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/adapter/ChatRecyclerAdapter.kt
> +    inner class BottomViewHolder(private val binding: SendFromMessageBinding) :
done

2023-04-20 07:53 UTC, Gio481 requested changes

2023-04-20 07:53 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/data/repository/DataStoreRepositoryImpl.kt
> +    }
dataStore ცალკე კლასი გააკეთე და რეპოზიტორში ეგ კლასი ჩააწოდე კონსტრუქტორში

2023-04-20 07:53 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/di/DataStoreModule.kt
> +}
ამის მოდულიც იგივნაირად გააკეთე როგორც რუმის, სურათის მსგავსად 
![datastoremodule](https://user-images.githubusercontent.com/70803715/233298149-ce50951a-bbe0-4135-a171-89968961eff2.JPG)

2023-04-20 08:52 UTC, gioqemoklidze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
ვიუმოდელის ცვლადი დააპრივეითე

2023-04-20 09:52 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/repository/DataStoreRepositoryImpl.kt
> +    }
done

2023-04-20 09:52 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/di/AppModule.kt
> +}
done

2023-04-20 09:55 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
` protected abstract val viewModel: VM` მაგას ვერ მივწერ private-ს იმიტომ რომ abstract არის
`override val viewModel by viewModel<ChatFragmentViewModel>()` და აქ იმიტომ რომ ოვერაიდი 

@gioqemoklidze , ვერ მივხდვი რომელ ცვლადს გულისხმობ

2023-04-20 10:39 UTC, Gio481 requested changes

2023-04-20 10:39 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/data_store/DataStoreManager.kt
> +    }
ამ ფუნქციას saveValue შეგიძლია ან რამე მსგავსი და პარამეტრად სტრინგი key და value ზე dayMode, enum კლასი გქონდეს Day, Night ან Light, Dark და მაგის ველიუ ჩააწოდე

2023-04-20 10:39 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/data_store/DataStoreManager.kt
> +    }
getFlow -> getValue და შეგიძლია ასე დაწერო

fun getValue(key: String): Flow<String> {
        val preferences = dataStore.data.map { preference ->
            preference[stringPreferencesKey(key)] ?: defaultValue
        }
        return preferences
    }

რეპოზიტორშიც მხოლოდ ფუნცქიას გამოიძახებ და emit ვმ ში იზავ

2023-04-20 10:41 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseDiff.kt
> +package com.example.chatapp_spaceintern.presentation.base
ამის ბეისში გატანა არ გინდა შეგიძლია util ში გაიტანო

2023-04-20 10:46 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseDiff.kt
> +package com.example.chatapp_spaceintern.presentation.base
done

2023-04-20 10:50 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/data_store/DataStoreManager.kt
> +    }
done, thanks!!

2023-04-20 10:51 UTC, gioqemoklidze commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
>      abstract fun onBind()
თვითნ ეგ ცვლადი შეგიძლია რომ  პრაივათი გახადო და ცალკე კიდევ ერთ ცვლადი შექმნა რომელიც ვიუმოდელის კლასს ამიღებს და მერე ონქრიეითში getViewModel ით ამოიღო ეგ შენი ვიუმოდელი სადღაც ესეთ ვარიანტი რა   
```kotlin
    lateinit var viewModel: VM
    abstract val viewModelClass: KClass<VM>

    override fun onCreate(savedInstanceState: Bundle?) {
        viewModel = getViewModel(clazz = viewModelClass)

        super.onCreate(savedInstanceState)
    }

```

```kotlin

    lateinit var viewModel: VM
    abstract fun getViewModelClass(): Class<VM>

    override fun onCreate(savedInstanceState: Bundle?) {
        viewModel = getViewModel(clazz = getViewModelClass())

        super.onCreate(savedInstanceState)
    }

```

2023-04-20 11:06 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/local/data_store/DataStoreManager.kt
> +    }
done

2023-04-20 13:20 UTC, Gio481 approved these changes

2023-04-20 14:56 UTC, AnaRusadze approved these changes

2023-04-20 17:07 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/data/repository/DataStoreRepositoryImpl.kt
> +                flow.firstOrNull() ?: ""
ერთი return წაუშალე ორი რათ გინდა

2023-04-20 17:09 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/domain/local/repository/ChatMessageRepository.kt
> +    suspend fun insertAll(message: MessageModel)
ერთ მესიჯს აწვდი და insertAll ქვია ფუნქციას insertMessage გადაარქვი აქაც და დანარჩენებშიც

2023-04-20 17:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/data/repository/DataStoreRepositoryImpl.kt
> +                flow.firstOrNull() ?: ""
შემთხვევით გამომრჩა, done

2023-04-20 17:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/local/repository/ChatMessageRepository.kt
> +    suspend fun insertAll(message: MessageModel)
done

2023-04-20 17:37 UTC, Gio481 requested changes

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/DayNightPreferencesUseCase.kt
> +}
ეს არღვევს სოლიდის პრიცნიპებიდან ერთ ერთს აბა რომელს არღვევს და რატო და როგორ უნდა გაასწორო 😃

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
> +    abstract fun onBind(viewModel: VM)
onBindViewModel ფუნცქიის სახელი

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
შეგიძლია ამ ფრაგმენტს გადმოაყოლო არგუმენტად TOP ან BOTTOM და ეგ ჩააწოდო ადაპტერსაც

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
ეს ფუნქცია მაღლა აიტანე

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    )
ეს და ზოგადად პრაივაით ფუნქციები onBindViewModel ფუნქციის ქვემოთ დაწერე ხოლმე, ამ შემთხვევაში ეს ფუნქცია ფრაგმენტიდან წასაშლელია და ვმშია გასატანი, აიდს ნალს აწვდი თავისით აგენერირებს ხო ამიტო პირდაპირ MessageModel შეგიძლია გაუწერო აიდი 1 დეფოლტად მაინც არ აქვს ხო მნიშვნელობა

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +            }
ასეთი რამე გააკეთე და იფ ელსები აღარ გექნება, ვმში გამოდგი ფუნქცია, აქ რო დააწვები ან სეივმესიჯის ფლოუს თუ იყენებ მაშინ მაგას გაუკეთე emit ან ინტერნეტის ერორის ფლოუს და ორივე დააქოლექთე და რომლის ემიტიც მოხდება ქლიქის დროს ის გაეშვება

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +        }
ეს ჩეკი ხო აქ აღარ გინდა

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
ამ ფუნქციას აზრი არ აქ პირდაპირ viewModel.sendMessage დაწერე შესაბამის ადგილას

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
აი ამის ექსთენშენი უნდა გააკეთო ფრაგმენტის და დაწერ პირდაპირ lifecycleScope{}

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/CoroutineScopeExtension.kt
> +fun ViewModel.launchWithViewModelScope(
სახელი პირდაპირ viewModelScope{} და ზედა ფუნქციაზე ზემოთ რაც დაგიწერე კომენტარი ან თუ ესეც გჭირდება ესეც გქონდეს და სახელიც შეამოკლე

2023-04-20 17:37 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/DateExtansion.kt
> +}
getCurrentTime()

2023-04-20 17:43 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
ფლოუში მოაქციე ეს ლისტიც და დაქოლექთების დროს გაუკეთე საბმიტ ლისტი და ეცადე რო ყველაფერი რაც შესაძლებელია უნდა მოაქციო ფლოუში ან ლაივდათაში რო მერე აობსერვო

2023-04-21 08:07 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/DayNightPreferencesUseCase.kt
> +}
Repository - Per feature, Use Case - Per function უნდა იყოს, მართალი ხარ 😓

2023-04-21 08:26 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/DayNightPreferencesUseCase.kt
> +}
SRP, use case - per function უნდა იყოს

2023-04-21 08:29 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
როგორც ვიცი არ ისე კარგი პრაქტიკა როცა ფრაგმენტებს არგუმენტს ვაწვდით, თან ერთ ერთ ვერსიაში უკვე მქონდა მსგავსი ლოგიკა და იქრაშებოდა  როცა თემას ვუცვლიდი ან ეკრანის ორიენტაციას

2023-04-21 09:00 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/SendMessageUseCase.kt
> +}
აქ ვერ მივხდი რაში არის პრობლემა ? თუ ფუნქციის სახელს გულისხობ ის კიდე გუშინ შევცვალე

2023-04-21 09:26 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/DayNightPreferencesUseCase.kt
> +}
არა, დეფენდენსი ინვერშენი, მარტივად რო ვთქვათ ამის იმპლემენტაცია კი არა ინტერფეის უნდა ხედავდეს სხვა კლასი სადაც ამას იყენებ შენ გჭირდება, ინტერფეისი და მისი იმპლემენტაცია და დეფენდენსი ინჯეწშენით უკვე ინტერფეის ჩააინჯექთებ სხვაგან

2023-04-21 09:26 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/SendMessageUseCase.kt
> +}
ზედა კომენტარში დავწერე

2023-04-21 09:48 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
რატო არაა კარგი პრაქტიკა ? რო იქრაშება უნდა გაფიქსო :დ

2023-04-21 10:16 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
მაშინ არ ვიცი როგორ გავაკეთო, როცა დრო მექნება მაშინ თავიდან შევეცდები

2023-04-21 10:28 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/DayNightPreferencesUseCase.kt
> +}
მე მგონი მივხვდი, მაგის იმედი მაქვს 🙃🙃

2023-04-21 10:28 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/domain/use_case/SendMessageUseCase.kt
> +}
done ?

2023-04-21 10:29 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/MainActivityViewModel.kt
> +        viewModelScope.launch {
done

2023-04-21 10:29 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/base/BaseFragment.kt
> +    abstract fun onBind(viewModel: VM)
done

2023-04-21 10:29 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +        }
გამომრჩა 😅, done

2023-04-21 10:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
მართალი ხარ, done

2023-04-21 10:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
done

2023-04-21 10:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/CoroutineScopeExtension.kt
> +fun ViewModel.launchWithViewModelScope(
done

2023-04-21 10:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/utils/extension/DateExtansion.kt
> +}
done

2023-04-21 10:30 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
done ?

2023-04-21 11:09 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +        }
ფრაგმენტდიან ემიტ არაა სწორი

2023-04-21 11:16 UTC, Gio481 commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
ამას რო უსეტავ ახლა აქ მარტო დაერორებული მესიჯი არ დაესეტება ?

2023-04-21 11:20 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
კი მასე მაქვს, სხვანაირად ვერ გავაკეთე ჯერ

2023-04-23 13:21 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    )
done

2023-04-23 13:21 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +    }
done, check new pr

2023-04-23 13:23 UTC, iTarley commented on app/src/main/java/com/example/chatapp_spaceintern/presentation/chat_screen/ui/ChatFragment.kt
> +            }
როცა გამოვასწორებ მთლიანად ინტერნეტის დახენდლვას , მაგას მივხედავ

2023-04-24 08:29 UTC, GiorgiMamagulashvil1 approved these changes

2023-04-24 08:36 UTC, merged