[CMOB-1321]One viewholder recyclerview
iTarley/ChatApp-SpaceIntern pull request #3
Opened 2023-04-23 13:19 UTC by iTarley

Changes:
Application package name refactoring,
MainActivity and ChatFragment viewmodels refactoring,
Refactored ChatRecyclerAdapter.kt from two viewholders to one,
Moved some functions to ViewModel,
better namings for classes (BaseFragment,DataBaseModule,DataStoreModule)

!!! 78 FILES CHANGED BECAUSE OF PACKAGE NAME REFACTORING !!!

Problems: 
Scroll to bottom,
Internet handling

https://spaceneobank.atlassian.net/browse/CMOB-1321

2023-04-23 17:42 UTC, Gio481 requested changes

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/res/values/dimens.xml
>      <dimen name="margins_paddings">10dp</dimen>
10dp რატო ქვია margins_paddings ? აღარ უნდა დაიწეროს უკვე ასეთი კომენტარები

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/res/layout/send_message.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
ყველა ტექსტვიუს უნდა სტილი და არც ესაა გამონაკლისი ასევე textSize რა სახელი ქვია რა არის ?

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/res/layout/send_message.xml
> +        android:layout_marginBottom="@dimen/dimen_15dp"
marginBottom აღარ უნდა

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/res/drawable/rectangle_bubble.xml
> +    <corners android:radius="25dp" />
ჰარდად გიწერია

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/viewmodel/ChatViewModel.kt
> +    }
ცარიელ სტრინგზე არ გინდა შემოწმება ?

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/viewmodel/ChatViewModel.kt
> +        id = null,
ნალი მოდელშივე გადაეცი და აქ ხო აღარ გინდა

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/ui/ChatFragment.kt
> +            }
ეს ხო არ მუშაობს და ამის ჩამერჯვას რა აზრი იქნება თუ მაინც ახალად გექნება გასაკეთებელი, რატო ვერ ჰენდლავ რა პრობლემას ხედავ და ვერ აგვარებ ?

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/ui/ChatFragment.kt
> +                }
ლოგიკას აკლია რაღაც და გაუმჯობესაც უნდა.
1. imageBtnView რა სახელია send აკეთებ მესიჯის და არაფერ კავშირშია ბათონის სახელი და ფუნქცია ერთმანეთან.
2. ჯერ უნდა შემოწმდეს დაწერილი აქვს თუ არა მესიჯი იუზერს და მერე შემოწმდეს ინტერნეტი აქვს თუ არა
3. შენ უნდა გქონდეს ორი ფლოუ, ამ ბათონს რო დააწვები არის თუ არა ინტერნეტი ეგ უნდა შეამოწმო ვმში და შესაბამის ფლოუში ჩასეტო მნიშვნელობა, ფრაგმენტში ორივეს დააქოლექთებ და ყოველ ჯერზე შესაბამის ფლოუში ხო ჩაესეტება და შესაბამისი ფუნქცია გაეშვება

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/viewmodel/ChatViewModel.kt
> +        sender = tag,
აქ ვერ ხვდები რაღაცას, სტრინგში რატო გადაგყავს პირდაპირ ენამის ტიპი გქონდეს

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/viewmodel/ChatViewModel.kt
> +        time = getCurrentTime()
ეხლა დროში დაფორმატირებულ სტრინგს ხო ინახავ ? ეგ არასწორია, პირდაპირ დრო შეინახე ლონგად და როგორც გინდა ისე დაფორმატირებულს დაახატინებ

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/model/UserEnum.kt
> +}
TopUser, BottomUser

2023-04-23 17:42 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/utils/ThemeModeEnum.kt
>      DAY_MODE("day"), NIGHT_MODE("night")
Day, Night

2023-04-24 08:58 UTC, iTarley commented on app/src/main/java/com/space/chatapp/utils/ThemeModeEnum.kt
>      DAY_MODE("day"), NIGHT_MODE("night")
Done, incoming in next commit

2023-04-24 08:58 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/viewmodel/ChatViewModel.kt
> +        time = getCurrentTime()
Done

2023-04-24 08:58 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/viewmodel/ChatViewModel.kt
> +        time = getCurrentTime()
In next commit

2023-04-24 08:59 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/ui/ChatFragment.kt
> +                }
აქ პირველი ირო გამოვასწორე, მაგრამ როგორ შევამოწმო ინტერნეტი ვიუმოდელში კონტექსტის გარეშე ჯერ არ ვიცი, დაველოდები სხვა ინტერნებს და გამოვასწორებ

2023-04-24 09:00 UTC, iTarley commented on app/src/main/res/layout/send_message.xml
> +        android:layout_marginBottom="@dimen/dimen_15dp"
მართალი ხარ, done

2023-04-24 09:03 UTC, iTarley commented on app/src/main/res/values/text_style.xml
> +        <item name="android:padding">@dimen/dimen_16dp</item>
Done, in next commit ( დენი არ მაქცს რომ ავფუშო )

2023-04-24 09:27 UTC, Gio481 commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/ui/ChatFragment.kt
> +                }
https://www.youtube.com/watch?v=To9aHYD5OVk ეს ნახე ინტერნეზე აბა თუ გამოგადგება

2023-04-24 18:08 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/ui/ChatFragment.kt
> +                }
ამას გამოვასწორებ  - დავწერ ახალ ბრენჩზე აქ უკვე არ მინდა მაგის გაშვება

2023-04-25 13:23 UTC, GiorgiMamagulashvil1 requested changes

2023-04-25 15:59 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/adapter/ChatRecyclerAdapter.kt
> +            root.scaleX = if (sender.name == item.sender.name) 1f else -1f
done

2023-04-25 15:59 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/viewmodel/ChatViewModel.kt
> +        id = null,
done

2023-04-26 07:52 UTC, Gio481 approved these changes

2023-04-26 08:22 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/data/repository/ChatMessageRepositoryImpl.kt
> +    override fun getAll() = dao.getAll().map { chat ->
getAll - სახელი დააკონკრეტე, რომ უფრო გასაგები იყოს რის გეთზეა საუბარი

2023-04-26 08:23 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/domain/local/repository/DataStoreRepository.kt
> +}
ჯობია, რომ დატასთორის კლასებს უბრალოდ დათასთორი კი არ ერქვას, არამედ რის დათას ინახავს ისიც მიუთითო, ასევე დატაბეიზის კლასშიც გაითვალისწინე იგივე

2023-04-26 08:26 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/domain/use_case/GetThemeStateUseCase.kt
> +package com.space.chatapp.domain.use_case
შეგიძლია იუსქეისების ფექეჯები შემდეგნაირად დაახარისხო:

theme:

 - get ->  (GetThemeStateUseCase, GetThemeStateUseCaseImpl)
 - save -> (SaveThemeStateUseCase, SaveThemeStateUseCaseImpl)

 message:

- send -> (SendMessageUseCase, SendMessageUseCaseImpl)
- show -> (ShowMessageUseCase, ShowMessageUseCaseImpl)

2023-04-26 08:30 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/presentation/MainActivity.kt
> +        }
drawable-ს მინიჭების გარდა ყველა ლოგიკა ვიუმოდელში უნდა იყოს

2023-04-26 08:30 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/presentation/MainActivity.kt
> +        }
კოდი დააფორმატირე

2023-04-26 08:32 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/presentation/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
ჯობია, რომ MainActivity-ს სახელში მიუთითო ზუსტად რისი ექთივითია. მეინის სახელს არ ვტოვებთ ხოლმე აპლიკაციაში. იგივე მეინვიუმოდელსაც. და ფექეჯებშიც გაანაწილე ui -> viewmodel ში. 
p.s viewmodel შეგიძლია შეამოკლო და vm დაწერო

2023-04-26 08:33 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/presentation/MainViewModel.kt
> +    fun dayNightHandling() {
handling ზოგადი სიტყვაა, შეგიძლია გამოიყენო update ან change, რადგან მიგვითითებს რომ განახლებასთან არის კავშირი
ასევე dayNight სადაც წერია, ყველგან ჯობია Theme-დ მოიხსენიო, რომ კოდი მზად იყოს მესამე თემის დასამატებლადაც ბევრი რეფაქტორის გარეშე

2023-04-26 08:34 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/adapter/ChatRecyclerAdapter.kt
> +package com.space.chatapp.presentation.chat_screen.adapter
ადაპტერი შეგიძლია ui ფექეჯის ქვეშ გადმოიტანო, რადგან ui-ს ნაწილია

2023-04-26 08:36 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/adapter/ChatRecyclerAdapter.kt
> +        const val SENDER_COLOR = R.color.purple_light
შეგიძლია ფერები არ შეინახო კონსტანტ ცვლადებში და პირდაპირ გამოიყენო, ვორნინგსაც აიცილებ თავიდან

2023-04-26 08:36 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/adapter/ChatRecyclerAdapter.kt
> +        const val FLIPPED_SCALE_FACTOR = -1f
სქეილის ცვლადები მარტო ამ კლასში გამოიყენება, ამიტომ private მიუწერე

2023-04-26 08:38 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/utils/extension/DateExtension.kt
> +fun Long.convertTimeToPattern(): String {
pattern-ის ნაცვლად შეგიძლია Format გამოიყენო, მაგრამ შენ როგორც გინდა

2023-04-26 08:40 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/utils/extension/ImageViewExtension.kt
> +fun ImageView.setTint(color:Int){
პატარა შენიშვნა, მაგრამ ქოლორის პარამეტრი Int თუ არის მიუთითე რომ რესურსს ელოდები, ანუ colorRes. იგივე შეგიძლია გაითვალისწინო drawableბზეც, როცა გამოიყენებ.

2023-04-26 08:41 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/utils/extension/StringExtension.kt
> +}
შეგიძლია ეს ექსთენშენი ჩაანაცვლო isNullOrEmpty()-თ

2023-04-26 08:42 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/utils/extension/TextViewExtension.kt
> +}
თუ იმიჯვიუსთვისაც და ტექსტვიუსთვისაც გჭირდება ტინტის ექსთენშენი, შეგიძლია View.-ის ექსთენშენი გახადო და ტექსტვიუზეც გამოიყენებ და იმიჯვიუზეც

2023-04-26 08:44 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/utils/extension/ViewModelExtension.kt
> +}
ვიუმოდელის ექსთენშენი ვიუმოდელთან შინაარსობრივად მიახლოებული უნდა იყოს. ახლა ამ ექსთენშენს ვერ გამოვიყენებთ იმ სხვა კლასში სადაც რამე ვიუმოდელთან წვდომა არ მაქვს. შეგიძლია უბრალო ფუნქცია დატოვო

2023-04-26 08:45 UTC, AnaRusadze commented on app/src/main/java/com/space/chatapp/utils/extension/СontextExtension.kt
> +}
ადრე მე გირჩიე კონტექსტის ექსთენშენის გაკეთება, მაგრამ უფრო კარგი იქნება თუ NetworkManager-ის კლასს შექმნი ან რამე მსგავსს და ეს ლოგიკა კლასის შიგნით იქნება

2023-04-26 08:47 UTC, iTarley commented on app/src/main/java/com/space/chatapp/utils/extension/СontextExtension.kt
> +}
ეგ უბრალოდ ამ ბრენჩს არ ეხება, სხვაზე მინდოდა მაგის გაკეთება

2023-04-26 09:51 UTC, iTarley commented on app/src/main/java/com/space/chatapp/utils/extension/DateExtension.kt
> +fun Long.convertTimeToPattern(): String {
![image](https://user-images.githubusercontent.com/95241918/234539200-05181af2-281b-496a-a62c-9655367cb7bc.png)
აქ რომ pattern წერია, მაგიტომ მასე დავარქვი

2023-04-26 10:01 UTC, shioandghuladze requested changes

2023-04-26 10:33 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/space/chatapp/presentation/model/ChatUser.kt
> +    TOP_USER, BOTTOM_USER
ctrl alt L

2023-04-26 10:41 UTC, iTarley commented on app/src/main/java/com/space/chatapp/data/repository/ChatMessageRepositoryImpl.kt
> +    override fun getAll() = dao.getAll().map { chat ->
done

2023-04-26 10:41 UTC, iTarley commented on app/src/main/java/com/space/chatapp/domain/local/repository/DataStoreRepository.kt
> +}
done

2023-04-26 10:41 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/MainActivity.kt
> +        }
done

2023-04-26 10:42 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/MainActivity.kt
> +        }
done

2023-04-26 10:42 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/MainActivity.kt
> +class MainActivity : AppCompatActivity() {
done, არ მიყვარს ეს შემოკლებული სახელები

2023-04-26 10:43 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/MainViewModel.kt
> +    fun dayNightHandling() {
done

2023-04-26 10:43 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/adapter/ChatRecyclerAdapter.kt
> +package com.space.chatapp.presentation.chat_screen.adapter
done

2023-04-26 10:46 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/adapter/ChatRecyclerAdapter.kt
> +        const val FLIPPED_SCALE_FACTOR = -1f
გამომრჩა, done

2023-04-26 10:46 UTC, iTarley commented on app/src/main/java/com/space/chatapp/utils/extension/ImageViewExtension.kt
> +fun ImageView.setTint(color:Int){
done

2023-04-26 10:47 UTC, iTarley commented on app/src/main/java/com/space/chatapp/utils/extension/StringExtension.kt
> +}
მართლაც, რატომ დავწერე უკვე არც მახსოვს

2023-04-26 10:48 UTC, iTarley commented on app/src/main/java/com/space/chatapp/utils/extension/TextViewExtension.kt
> +}
image view-ზე მაქვს imageTintList და ტექსტზე backgroundTintList და ეს ორი ფუნქცია სხვადასხვანაირად სეტავს

2023-04-26 10:49 UTC, iTarley commented on app/src/main/java/com/space/chatapp/utils/extension/ViewModelExtension.kt
> +}
done

2023-04-26 10:51 UTC, iTarley commented on app/src/main/java/com/space/chatapp/data/local/entity/ChatEntity.kt
>      @ColumnInfo(name = "time")
done

2023-04-26 10:54 UTC, iTarley commented on app/src/main/java/com/space/chatapp/data/local/AppDatabase.kt
>      exportSchema = true
done

2023-04-26 10:54 UTC, iTarley commented on app/src/main/java/com/space/chatapp/domain/use_case/SaveThemeStateUseCase.kt
> +    suspend fun invoke(dayMode: ChatThemeMode)
done

2023-04-26 11:02 UTC, AleksandreGalogreBaramidze approved these changes

2023-04-26 13:50 UTC, iTarley commented on app/src/main/java/com/space/chatapp/presentation/chat_screen/adapter/ChatRecyclerAdapter.kt
> +        const val SENDER_COLOR = R.color.purple_light
review-ზე რომ ზურა მიპასუხა, გავიგე რასშია პრობლემა

2023-05-01 16:18 UTC, merged